application: demo
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: app.py

- url: /makenote
  script: app.py

- url: /count
  script: app.py

- url: /log
  script: app.py

- url: /dummy
  script: dummy.py
  login: required
  secure: always

- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/xmpp/message/chat/
  script: app.py

- url: .*
  script: dummy.py
