application: demo
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:

- url: /(.*\.(gif|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(gif|jpg|png))
  expiration: 5h

- url: /static
  static_dir: static

- url: /
  script: app.py

- url: /count
  script: app.py

- url: /invite
  script: app.py

- url: /log
  script: app.py

- url: /makenote
  script: app.py

- url: /getnote
  script: app.py

- url: /dummy
  script: dummy.py
  login: required
  secure: always

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/xmpp/message/chat/
  script: app.py

- url: .*
  script: dummy.py
